#spring.application.name=StringasPrimarykay

# PostgreSQL Database Configuration
spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5432/Company
spring.datasource.postgres.username=Employeess
spring.datasource.postgres.password=Dnayneshwar
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect.postgres=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibenate.auto.ddl=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


